Migrate to esbuild
Annoraaq/phaser-grid-movement-plugin pull request #70
Opened 2021-03-12 18:00 UTC by splashsky

This PR addresses #69 (nice), implementing the migration to the `esbuild` bundler. A lot of the Webpack bloat is removed and the list of required dependencies is now much shorter.

This PR also accidentally includes the removal of the now-useless `docs/` directory, which was meant to take effect when the new docs were pushed through.

See issue #69 in regards to this PR's functionality - a working example of the `esbuild` build can be found there.

2021-03-12 18:37 UTC, Annoraaq requested changes
Impressive how much config code we can save.

I found 2 problems:

1. TypeScript dev dependency needs to stay, otherwise the tests can't run (`npm test`)
2. Because the tsconfig.json is missing there are 2 issues:
 2.1 the tests don't run because of the '--downlevelIteration' flag
 2.2 the type declaration files are not being generated (.d.ts files).
 
I think we can't get rid of the tsconfig.json because it is necessary for some ts settings.

2021-03-12 19:04 UTC, splashsky commented
I re-added the `typescript` dev dependency and brought back `tsconfig`, ran the tests successfully on my end. Check it out and see if we're good to go 😄

2021-03-12 19:44 UTC, Annoraaq commented
@splashsky The tests run fine now. But if I run `npm run build` I still don't get the declaration files despite the setting in the tsconfig.

I found this issue here:

https://github.com/evanw/esbuild/issues/95

They suggest to create the declaration files in a separate step with `tsc --emitDeclarationOnly`.

If I chain the commands in the package.json like this:

```
"scripts": {
        "build": "tsc --emitDeclarationOnly && esbuild src/main.ts --bundle --minify --global-name=GridMovementPlugin --outfile=dist/GridMovementPlugin.min.js"
    },
```

It creates the declaration files. However, I still need to manually copy the `GridMovementPlugin.d.ts` file to the `dist` folder.

2021-03-12 19:56 UTC, Annoraaq commented
we could add another dependency to do that (i.e. https://www.npmjs.com/package/copyfiles)

2021-03-12 20:02 UTC, splashsky commented
Actually, I was able to add a small modification to the build script that generates type declarations and dumps them into `dist/`, although it generates `.d.ts` files for *everything* in `src/`. Is this expected behavior? Should I be dumping the declarations into `src/` instead?

2021-03-13 08:08 UTC, Annoraaq requested changes
Please turn back the indentation. But the rest works fine. Actually I found out that it is even better to have all the .d.ts files around because they are including each other.

So type support should be better now. 🙂

2021-03-14 16:44 UTC, splashsky commented
The recent PRs kind of went beyond the scope of this little project, but I've got prettier and eslint set up here as well. Tested them in the `dev` script and they're working fine - builds also are good!

Sorry about the spaces - my IDE is fully set up to do everything in 4 spaces automatically so I didn't even notice 🤣

2021-03-15 10:01 UTC, Annoraaq commented
@splashsky with "recent PRs" you mean adding eslint and prettier?

I never heard that using prettier and eslint depends on the size on the project before. Despite being useful for a single person already, their true advantage shows when having more than one person working at the code.

2021-03-15 10:16 UTC, Annoraaq requested changes

2021-03-15 10:16 UTC, Annoraaq commented on tsconfig.json
>    "include": ["**/*.ts"],
```suggestion
  "include": ["**/*.ts"],
  "exclude": [
    "./dist/**/*"
  ]
```

2021-03-15 10:16 UTC, Annoraaq commented on tsconfig.json
>    "include": ["**/*.ts"],
I found out we need to explude the dist directory from the input of the tsc. Otherwise the build will error if there are already files in dist dir.

2021-03-15 10:58 UTC, splashsky commented
> 
> 
> @splashsky with "recent PRs" you mean adding eslint and prettier?
> 
> I never heard that using prettier and eslint depends on the size of the project before. Despite being useful for a single person already, their true advantage shows when having more than one person working at the code.

I apologize, I meant little project as in this PR specifically - but I did get that last note resolved so maybe we're good to go? 😄

2021-03-15 11:06 UTC, Annoraaq commented
> > @splashsky with "recent PRs" you mean adding eslint and prettier?
> > I never heard that using prettier and eslint depends on the size of the project before. Despite being useful for a single person already, their true advantage shows when having more than one person working at the code.
> 
> I apologize, I meant little project as in this PR specifically - but I did get that last note resolved so maybe we're good to go? 😄

No, I apologize 🙂  I now get what you meant. Now everything works fine. We are good to go. Excellent work and thank you for your contribution. esbuild is blazingly fast.

2021-03-15 11:06 UTC, Annoraaq approved these changes

2021-03-15 11:08 UTC, Annoraaq commented
I can't merge it due to conflicts. Can you resolve them by merging the latest master into your branch? 
You can throw away all the files in docs because I also updated them on our gh-pages branch. The rest should be easy.

2021-03-15 15:00 UTC, merged

2021-03-15 15:01 UTC, splashsky commented
Whoops, accidentally merged this - still new to Git and was just trying to resolve the conflicts lol

Either way, conflicts were fixed and merged into master. 😄